---
name: 'Build'

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  schedule:
    - cron: '17 6 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node and Yarn
        uses: volta-cli/action@v4

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn run lint

      - name: Check formatting
        run: yarn run format-check

      - name: Test & Coverage
        run: yarn run coverage

      - name: Build
        run: yarn run build

      - name: HACS build validation
        uses: 'hacs/action@21.12.1'
        with:
          category: 'plugin'

          # Don't attempt to load into HACS (as it loads the release, not the
          # build).
          ignore: 'hacs'

      - name: Upload javascript
        uses: actions/upload-artifact@v4
        with:
          name: frigate-hass-card
          path: dist/*.js

      # When this issue is fixed, it would be useful to upload visualizations:
      # https://github.com/actions/upload-artifact/issues/14
      # - name: Upload visualizations
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: frigate-hass-card
      #     path: visualizations/*.html
